import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const sampleStudentsData = [
  {
    firstName: "Aarav",
    lastName: "Sharma",
    gender: "MALE",
    bloodGroup: "A+",
    category: "General",
    house: "Ganga",
    dob: new Date("2014-05-12"),
    fatherName: "Rajesh Sharma",
    fatherPhone: "9839012345",
    fatherEmail: "rajesh.sharma@example.com",
    fatherOccupation: "Software Engineer",
    motherName: "Sunita Sharma",
    motherPhone: "9839012346",
    currentAddress: "12/450, Civil Lines",
    currentPincode: "208001",
    city: "Kanpur",
    classNameWant: "Class VI",
    sectionNameWant: "A",
  },
  {
    firstName: "Ananya",
    lastName: "Verma",
    gender: "FEMALE",
    bloodGroup: "B+",
    category: "General",
    house: "Yamuna",
    dob: new Date("2015-08-24"),
    fatherName: "Vikram Verma",
    fatherPhone: "9415011223",
    fatherEmail: "vikram.verma@example.com",
    fatherOccupation: "Chartered Accountant",
    motherName: "Pooja Verma",
    motherPhone: "9415011224",
    currentAddress: "7/102, Swaroop Nagar",
    currentPincode: "208002",
    city: "Kanpur",
    classNameWant: "Class V",
    sectionNameWant: "B",
  },
  {
    firstName: "Vihaan",
    lastName: "Gupta",
    gender: "MALE",
    bloodGroup: "O+",
    category: "General",
    house: "Jhelum",
    dob: new Date("2012-03-15"),
    fatherName: "Alok Gupta",
    fatherPhone: "9838022334",
    fatherEmail: "alok.gupta@example.com",
    fatherOccupation: "Business Owner",
    motherName: "Meenakshi Gupta",
    motherPhone: "9838022335",
    currentAddress: "117/K/42, Sarvodaya Nagar",
    currentPincode: "208005",
    city: "Kanpur",
    classNameWant: "Class VIII",
    sectionNameWant: "A",
  },
  {
    firstName: "Ishaan",
    lastName: "Patel",
    gender: "MALE",
    bloodGroup: "AB+",
    category: "OBC",
    house: "Chenab",
    dob: new Date("2016-11-04"),
    fatherName: "Suresh Patel",
    fatherPhone: "9793033445",
    fatherEmail: "suresh.patel@example.com",
    fatherOccupation: "Bank Manager",
    motherName: "Rekha Patel",
    motherPhone: "9793033446",
    currentAddress: "45/A, Kidwai Nagar",
    currentPincode: "208011",
    city: "Kanpur",
    classNameWant: "Class IV",
    sectionNameWant: "A",
  },
  {
    firstName: "Diya",
    lastName: "Srivastava",
    gender: "FEMALE",
    bloodGroup: "A-",
    category: "General",
    house: "Ravi",
    dob: new Date("2013-09-18"),
    fatherName: "Amit Srivastava",
    fatherPhone: "9839144556",
    fatherEmail: "amit.sri@example.com",
    fatherOccupation: "Doctor",
    motherName: "Dr. Ritu Srivastava",
    motherPhone: "9839144557",
    currentAddress: "88/2, Mall Road",
    currentPincode: "208004",
    city: "Kanpur",
    classNameWant: "Class VII",
    sectionNameWant: "B",
  },
  {
    firstName: "Kabir",
    lastName: "Singh",
    gender: "MALE",
    bloodGroup: "O+",
    category: "General",
    house: "Sutlej",
    dob: new Date("2010-01-30"),
    fatherName: "Harpreet Singh",
    fatherPhone: "9450055667",
    fatherEmail: "harpreet.singh@example.com",
    fatherOccupation: "Industrialist",
    motherName: "Gurpreet Kaur",
    motherPhone: "9450055668",
    currentAddress: "14/112, Tilak Nagar",
    currentPincode: "208002",
    city: "Kanpur",
    classNameWant: "Class X",
    sectionNameWant: "A",
  },
  {
    firstName: "Aditi",
    lastName: "Mishra",
    gender: "FEMALE",
    bloodGroup: "B+",
    category: "General",
    house: "Ganga",
    dob: new Date("2017-04-14"),
    fatherName: "Pradeep Mishra",
    fatherPhone: "9838266778",
    fatherEmail: "pradeep.mishra@example.com",
    fatherOccupation: "Advocate",
    motherName: "Seema Mishra",
    motherPhone: "9838266779",
    currentAddress: "128/90, Kakadeo",
    currentPincode: "208025",
    city: "Kanpur",
    classNameWant: "Class III",
    sectionNameWant: "A",
  },
  {
    firstName: "Reyansh",
    lastName: "Agarwal",
    gender: "MALE",
    bloodGroup: "A+",
    category: "General",
    house: "Yamuna",
    dob: new Date("2018-07-22"),
    fatherName: "Manoj Agarwal",
    fatherPhone: "9794077889",
    fatherEmail: "manoj.agarwal@example.com",
    fatherOccupation: "Textile Businessman",
    motherName: "Shilpa Agarwal",
    motherPhone: "9794077890",
    currentAddress: "15/67, Arya Nagar",
    currentPincode: "208002",
    city: "Kanpur",
    classNameWant: "Class II",
    sectionNameWant: "B",
  },
  {
    firstName: "Saisha",
    lastName: "Kapoor",
    gender: "FEMALE",
    bloodGroup: "O-",
    category: "General",
    house: "Jhelum",
    dob: new Date("2019-12-10"),
    fatherName: "Rohan Kapoor",
    fatherPhone: "9839388990",
    fatherEmail: "rohan.kapoor@example.com",
    fatherOccupation: "Architect",
    motherName: "Neha Kapoor",
    motherPhone: "9839388991",
    currentAddress: "24/15, Pandu Nagar",
    currentPincode: "208005",
    city: "Kanpur",
    classNameWant: "Class I",
    sectionNameWant: "A",
  },
  {
    firstName: "Arjun",
    lastName: "Yadav",
    gender: "MALE",
    bloodGroup: "B+",
    category: "OBC",
    house: "Chenab",
    dob: new Date("2011-06-05"),
    fatherName: "Dinesh Yadav",
    fatherPhone: "9415499001",
    fatherEmail: "dinesh.yadav@example.com",
    fatherOccupation: "Civil Services Officer",
    motherName: "Anita Yadav",
    motherPhone: "9415499002",
    currentAddress: "C-14, Officers Colony, Cantt",
    currentPincode: "208004",
    city: "Kanpur",
    classNameWant: "Class IX",
    sectionNameWant: "A",
  },
  {
    firstName: "Myra",
    lastName: "Joshi",
    gender: "FEMALE",
    bloodGroup: "AB-",
    category: "General",
    house: "Ravi",
    dob: new Date("2015-02-18"),
    fatherName: "Sanjay Joshi",
    fatherPhone: "9838500112",
    fatherEmail: "sanjay.joshi@example.com",
    fatherOccupation: "Professor",
    motherName: "Suman Joshi",
    motherPhone: "9838500113",
    currentAddress: "IIT Kanpur Campus, House 402",
    currentPincode: "208016",
    city: "Kanpur",
    classNameWant: "Class V",
    sectionNameWant: "A",
  },
  {
    firstName: "Devansh",
    lastName: "Trivedi",
    gender: "MALE",
    bloodGroup: "O+",
    category: "General",
    house: "Sutlej",
    dob: new Date("2013-10-29"),
    fatherName: "Anand Trivedi",
    fatherPhone: "9793611223",
    fatherEmail: "anand.trivedi@example.com",
    fatherOccupation: "Manager, BHEL",
    motherName: "Priyanka Trivedi",
    motherPhone: "9793611224",
    currentAddress: "56/12, Barra 2",
    currentPincode: "208027",
    city: "Kanpur",
    classNameWant: "Class VII",
    sectionNameWant: "A",
  },
  {
    firstName: "Avani",
    lastName: "Saxena",
    gender: "FEMALE",
    bloodGroup: "A+",
    category: "General",
    house: "Ganga",
    dob: new Date("2014-01-08"),
    fatherName: "Gaurav Saxena",
    fatherPhone: "9839722334",
    fatherEmail: "gaurav.saxena@example.com",
    fatherOccupation: "IT Consultant",
    motherName: "Vandana Saxena",
    motherPhone: "9839722335",
    currentAddress: "90/4, Azad Nagar",
    currentPincode: "208002",
    city: "Kanpur",
    classNameWant: "Class VI",
    sectionNameWant: "B",
  },
  {
    firstName: "Rudra",
    lastName: "Tripathi",
    gender: "MALE",
    bloodGroup: "B-",
    category: "General",
    house: "Yamuna",
    dob: new Date("2012-07-14"),
    fatherName: "Mahesh Tripathi",
    fatherPhone: "9415833445",
    fatherEmail: "mahesh.tripathi@example.com",
    fatherOccupation: "Journalist",
    motherName: "Kavita Tripathi",
    motherPhone: "9415833446",
    currentAddress: "33/88, Govind Nagar",
    currentPincode: "208006",
    city: "Kanpur",
    classNameWant: "Class VIII",
    sectionNameWant: "B",
  },
  {
    firstName: "Kavya",
    lastName: "Chaudhary",
    gender: "FEMALE",
    bloodGroup: "O+",
    category: "OBC",
    house: "Jhelum",
    dob: new Date("2016-05-03"),
    fatherName: "Nitin Chaudhary",
    fatherPhone: "9838944556",
    fatherEmail: "nitin.chaudhary@example.com",
    fatherOccupation: "Real Estate Developer",
    motherName: "Poonam Chaudhary",
    motherPhone: "9838944557",
    currentAddress: "102, Shyam Nagar",
    currentPincode: "208013",
    city: "Kanpur",
    classNameWant: "Class IV",
    sectionNameWant: "B",
  },
  {
    firstName: "Atharv",
    lastName: "Pandey",
    gender: "MALE",
    bloodGroup: "A+",
    category: "General",
    house: "Chenab",
    dob: new Date("2017-09-27"),
    fatherName: "Satish Pandey",
    fatherPhone: "9794055667",
    fatherEmail: "satish.pandey@example.com",
    fatherOccupation: "Senior Accountant",
    motherName: "Archana Pandey",
    motherPhone: "9794055668",
    currentAddress: "77/14, Panki",
    currentPincode: "208020",
    city: "Kanpur",
    classNameWant: "Class III",
    sectionNameWant: "B",
  },
  {
    firstName: "Pari",
    lastName: "Rastogi",
    gender: "FEMALE",
    bloodGroup: "B+",
    category: "General",
    house: "Ravi",
    dob: new Date("2018-03-11"),
    fatherName: "Deepak Rastogi",
    fatherPhone: "9839166778",
    fatherEmail: "deepak.rastogi@example.com",
    fatherOccupation: "Jeweller",
    motherName: "Bhavna Rastogi",
    motherPhone: "9839166779",
    currentAddress: "5/201, Birhana Road",
    currentPincode: "208001",
    city: "Kanpur",
    classNameWant: "Class II",
    sectionNameWant: "A",
  },
  {
    firstName: "Shaurya",
    lastName: "Bhatia",
    gender: "MALE",
    bloodGroup: "AB+",
    category: "General",
    house: "Sutlej",
    dob: new Date("2009-12-01"),
    fatherName: "Sunil Bhatia",
    fatherPhone: "9415277889",
    fatherEmail: "sunil.bhatia@example.com",
    fatherOccupation: "Hotelier",
    motherName: "Simran Bhatia",
    motherPhone: "9415277890",
    currentAddress: "18/45, Lajpat Nagar",
    currentPincode: "208005",
    city: "Kanpur",
    classNameWant: "Class XI",
    sectionNameWant: "A",
  },
  {
    firstName: "Saanvi",
    lastName: "Dubey",
    gender: "FEMALE",
    bloodGroup: "O+",
    category: "General",
    house: "Ganga",
    dob: new Date("2010-08-16"),
    fatherName: "Ashok Dubey",
    fatherPhone: "9838388990",
    fatherEmail: "ashok.dubey@example.com",
    fatherOccupation: "Government Officer",
    motherName: "Madhu Dubey",
    motherPhone: "9838388991",
    currentAddress: "89/10, Yashoda Nagar",
    currentPincode: "208011",
    city: "Kanpur",
    classNameWant: "Class X",
    sectionNameWant: "B",
  },
  {
    firstName: "Aarush",
    lastName: "Kashyap",
    gender: "MALE",
    bloodGroup: "A-",
    category: "SC",
    house: "Yamuna",
    dob: new Date("2015-11-20"),
    fatherName: "Vinod Kashyap",
    fatherPhone: "9794499001",
    fatherEmail: "vinod.kashyap@example.com",
    fatherOccupation: "Railway Officer",
    motherName: "Sarita Kashyap",
    motherPhone: "9794499002",
    currentAddress: "105/B, Juhi Kalan",
    currentPincode: "208014",
    city: "Kanpur",
    classNameWant: "Class V",
    sectionNameWant: "B",
  },
];

async function main() {
  console.log("Seeding 20 realistic student records into DPS Echo database...");

  // 1. Get or create active session
  let session = await prisma.academicYear.findFirst({ where: { isCurrent: true } });
  if (!session) {
    session = await prisma.academicYear.findFirst({ orderBy: { name: "desc" } });
  }
  const sessionName = session?.name || "2026-2027";

  // 2. Fetch campuses
  const campuses = await prisma.campus.findMany({ include: { classes: { include: { sections: true } } } });
  if (campuses.length === 0) {
    throw new Error("No campus found in database. Run campus initialization first.");
  }

  const year = 2026;

  for (let i = 0; i < sampleStudentsData.length; i++) {
    const data = sampleStudentsData[i];
    const campus = campuses[i % campuses.length];

    // Find or fallback class
    let targetClass = campus.classes.find(
      (c) => c.name.toLowerCase() === data.classNameWant.toLowerCase()
    );
    if (!targetClass && campus.classes.length > 0) {
      targetClass = campus.classes[i % campus.classes.length];
    }

    if (!targetClass) {
      // Create fallback class
      targetClass = await prisma.class.create({
        data: {
          campusId: campus.id,
          name: data.classNameWant,
          numericGrade: parseInt(data.classNameWant.replace(/[^0-9]/g, "") || "5", 10),
          sequence: i + 1,
        },
        include: { sections: true },
      });
    }

    // Find or create section
    let targetSection = targetClass.sections.find(
      (s) => s.name.toUpperCase() === data.sectionNameWant.toUpperCase()
    );
    if (!targetSection) {
      targetSection = await prisma.section.create({
        data: {
          classId: targetClass.id,
          name: data.sectionNameWant,
          maxCapacity: 40,
        },
      });
    }

    const seq = 100 + i + 1;
    const scholarPrefix = campus.scholarIdPrefix || "DPS";
    const regPrefix = campus.registrationIdPrefix || "REG";

    const registrationNo = `${regPrefix}-${campus.code}-${year}-${String(seq).padStart(4, "0")}`;
    const scholarNo = `${scholarPrefix}-${campus.code}-${year}-${String(seq).padStart(4, "0")}`;
    const admissionNo = `${campus.code}/${year}/${seq}`;

    // Upsert student record
    const student = await prisma.student.upsert({
      where: { scholarNo },
      update: {
        firstName: data.firstName,
        lastName: data.lastName,
        gender: data.gender,
        bloodGroup: data.bloodGroup,
        category: data.category,
        house: data.house,
        dob: data.dob,
        academicYearIn: sessionName,
        currentAddress: data.currentAddress,
        currentPincode: data.currentPincode,
        city: data.city,
        emergencyContact: data.fatherPhone,
        status: "ACTIVE",
        campusId: campus.id,
        classId: targetClass.id,
        sectionId: targetSection.id,
        rollNo: (i % 35) + 1,
      },
      create: {
        registrationNo,
        registrationDate: new Date(),
        scholarNo,
        admissionNo,
        admissionDate: new Date("2026-04-01"),
        academicYearIn: sessionName,
        firstName: data.firstName,
        lastName: data.lastName,
        dob: data.dob,
        dobInWords: `${data.dob.getDate()} ${data.dob.toLocaleString("default", { month: "long" })} ${data.dob.getFullYear()}`,
        gender: data.gender,
        bloodGroup: data.bloodGroup,
        nationality: "Indian",
        religion: "Hinduism",
        category: data.category,
        motherTongue: "Hindi",
        studentMobile: data.fatherPhone,
        studentEmail: data.fatherEmail,
        campusId: campus.id,
        classId: targetClass.id,
        sectionId: targetSection.id,
        rollNo: (i % 35) + 1,
        house: data.house,
        status: "ACTIVE",
        currentAddress: data.currentAddress,
        currentPincode: data.currentPincode,
        permanentAddress: data.currentAddress,
        permanentPincode: data.currentPincode,
        city: data.city,
        emergencyContact: data.fatherPhone,
        howHeardAboutUs: "Website & Reference",
        registrationSource: "STAFF_PORTAL",
        registrationPaymentMode: "CASH",
        registrationFeePaid: 1000,
        registrationPaymentStatus: "PAID",
        guardians: {
          create: [
            {
              relation: "FATHER",
              name: data.fatherName,
              phone: data.fatherPhone,
              email: data.fatherEmail,
              occupation: data.fatherOccupation,
              isPrimary: true,
              address: data.currentAddress,
              pincode: data.currentPincode,
            },
            {
              relation: "MOTHER",
              name: data.motherName,
              phone: data.motherPhone,
              isPrimary: false,
              address: data.currentAddress,
              pincode: data.currentPincode,
            },
          ],
        },
      },
    });

    console.log(`[${i + 1}/20] Seeded Student: ${student.firstName} ${student.lastName} (${student.scholarNo}) - ${campus.name}`);
  }

  console.log("Successfully seeded 20 student records with complete details!");
}

main()
  .catch((e) => {
    console.error("Error seeding sample students:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
